---
settings:
  name: Well-architected dashboard
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: console-relnotes
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 시작하기
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 잘 설계된 대시보드에 대해 알아보기
      url: "/learn-well-architected-dashboard.html"
  - title: 지원되는 제품
    entries:
    - title: Amazon FSx for NetApp ONTAP
      entries:
      - title: 구성 분석
        url: "/fsx/configuration-analysis-fsx.html"
      - title: 파일 시스템 구성 개선
        url: "/fsx/improve-configurations-fsx.html"
    - title: Cloud Volumes ONTAP
      entries:
      - title: 구성 분석
        url: "/cvo/configuration-analysis-cvo.html"
      - title: 시스템 구성 개선
        url: "/cvo/improve-configurations-cvo.html"
  - title: 나만의 규칙 만들기
    entries:
    - title: 사용자 지정 규칙에 대해 알아보기
      url: "/learn-custom-rules.html"
    - title: 사용자 지정 규칙 만들기
      url: "/create-custom-rule.html"
    - title: 사용자 지정 규칙 관리
      url: "/manage-custom-rules.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
