---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: NetApp Console의 well-architected 대시보드의 새로운 기능을 알아보십시오. 
---
= NetApp Console의 잘 설계된 대시보드의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console의 well-architected 대시보드의 새로운 기능을 알아보십시오.



[[17-august-2026]]
== 2026년 8월 17일



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Google Cloud NetApp Volumes 지원(잘 설계된 대시보드)

NetApp Console 대시보드에서 이제 Google Cloud NetApp Volumes를 지원합니다. 스토리지 관리자는 스토리지 풀 및 구성 상태를 확인하고, 효율성, 비용, 성능, 안정성 및 보안을 개선하기 위한 권장 사항을 받아보고, 운영을 최적화하고 모범 사례를 따르기 위한 조치를 취할 수 있습니다.

link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Google Cloud NetApp Volumes에 대한 구성 분석"]에 대해 자세히 알아보십시오.



[[03-august-2026]]
== 2026년 8월 3일



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Microsoft Azure의 Cloud Volumes ONTAP 구성 수정, 해제 및 재활성화

NetApp Console의 잘 설계된 대시보드를 통해 이제 Cloud Volumes ONTAP 시스템에 대한 구성 권장 사항을 수정할 수 있습니다.

또한, 아키텍처 분석에서 하나 이상의 구성을 제외할 수 있습니다. 이를 통해 사용자 환경에 적용되지 않는 특정 구성을 무시할 수 있습니다.

나중에 해제된 구성을 포함하려면 잘 설계된 대시보드에서 다시 활성화할 수 있습니다. 이렇게 하면 구성이 분석에 복원되어 권장 사항 및 수정 사항을 확인할 수 있습니다.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Microsoft Azure의 Cloud Volumes ONTAP 구성 수정, 해제 및 재활성화"]



[[20-july-2026]]
== 2026년 7월 20일



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== NetApp Console의 잘 설계된 대시보드 소개

NetApp Console의 아키텍처 최적화 대시보드는 계정 및 지역 전반에 걸쳐 스토리지 시스템과 구성을 한눈에 볼 수 있도록 지원합니다. 이 대시보드는 운영 효율성을 극대화하는 데 도움이 되는 인사이트와 권장 사항을 제공합니다. 구성의 아키텍처 최적화 상태, 사용 중인 스토리지 유형에 대한 아키텍처 최적화 프레임워크의 핵심 요소별로 정리된 구성 문제, 그리고 구성 문제 및 권장 사항 목록을 확인할 수 있습니다.

link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["잘 설계된 대시보드"]에 대해 자세히 알아보십시오.

Console의 잘 설계된 대시보드는 link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Microsoft Azure의 Cloud Volumes ONTAP."]에서 이용할 수 있습니다.



[[build-your-own-custom-rules]]
=== 사용자 지정 규칙 만들기

조직 표준 및 NetApp 모범 사례를 준수하도록 사용자 지정 규칙을 이해하기 쉬운 언어로 작성하세요. 모의 실행을 통해 규칙을 테스트한 다음, 모든 환경에서 실행되도록 예약할 수 있습니다.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["사용자 지정 규칙에 대해 자세히 알아보기"]
