---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: NetApp Console의 well-architected 대시보드의 새로운 기능을 알아보십시오. 
---
= NetApp Console의 잘 설계된 대시보드의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console의 well-architected 대시보드의 새로운 기능을 알아보십시오.



[[17-august-2026]]
== 2026년 8월 17일



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Google Cloud NetApp Volumes 지원(잘 설계된 대시보드)

NetApp Console 대시보드에서 이제 Google Cloud NetApp Volumes를 지원합니다. 스토리지 관리자는 스토리지 풀 및 구성 상태를 확인하고, 효율성, 비용, 성능, 안정성 및 보안을 개선하기 위한 권장 사항을 받아보고, 운영을 최적화하고 모범 사례를 따르기 위한 조치를 취할 수 있습니다.

link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Google Cloud NetApp Volumes에 대한 구성 분석"]에 대해 자세히 알아보십시오.



[[03-august-2026]]
== 2026년 8월 3일



[[updated-configuration-names-for-fsx-for-ontap-in-the-well-architected-dashboard]]
=== FSx for ONTAP의 구성 이름이 잘 설계된 대시보드에서 업데이트되었습니다

NetApp Console의 잘 설계된 대시보드에 명확성과 일관성을 향상시키기 위해 FSx for ONTAP의 업데이트된 스토리지 구성 이름이 추가되었습니다.

다음 표는 기존 구성 이름과 잘 설계된 대시보드의 해당 새 구성 이름을 나열합니다.

[cols="1,1"]
|===
| 이전 구성 이름 | 새 구성 이름 


| 볼륨 백업 예약 | 볼륨 백업 


| SSD 용량 임계값 | SSD 용량 여유 공간 


| 파일 용량 임계값 | 파일 용량 여유 공간 


| 장기 보존 데이터의 신뢰성 | 복제 정책 레이블 


| 예약된 로컬 스냅샷 | 스냅샷 정책 


| 불필요한 백업 삭제 | 백업 만료 


| 불필요한 스냅샷 삭제 | 스냅샷 만료 


| SSD 용량 활용률 저하 | SSD 용량 과잉 프로비저닝 


| 비활성 블록 장치 | 비활성 블록 장치(LUN) 


| 콜드 데이터를 계층화하여 TCO 최적화 | 콜드 데이터 티어링 


| 볼륨 논리적 데이터 용량 보고 | 호스트에서 볼 수 있는 용량 보고 


| FlexGroup 볼륨 재조정 | FlexGroup 볼륨 재조정 


| FlexVol 볼륨 재조정 | FlexVol 볼륨 재조정 


| 캐시 관계 쓰기 모드 | FlexCache 쓰기 모드 


| 캐시 볼륨 크기 최적화 | FlexCache 복제본 크기 


| 볼륨에 대한 무단 접근 | 무단 iSCSI 볼륨 액세스 


| ARP/AI 비활성화됨 | 랜섬웨어 보호(ARP/AI) 
|===


[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Microsoft Azure의 Cloud Volumes ONTAP 구성 수정, 해제 및 재활성화

NetApp Console의 잘 설계된 대시보드를 통해 이제 Cloud Volumes ONTAP 시스템에 대한 구성 권장 사항을 수정할 수 있습니다.

또한, 아키텍처 분석에서 하나 이상의 구성을 제외할 수 있습니다. 이를 통해 사용자 환경에 적용되지 않는 특정 구성을 무시할 수 있습니다.

나중에 해제된 구성을 포함하려면 잘 설계된 대시보드에서 다시 활성화할 수 있습니다. 이렇게 하면 구성이 분석에 복원되어 권장 사항 및 수정 사항을 확인할 수 있습니다.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Microsoft Azure의 Cloud Volumes ONTAP 구성 수정, 해제 및 재활성화"]



[[20-july-2026]]
== 2026년 7월 20일



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== NetApp Console의 잘 설계된 대시보드 소개

NetApp Console의 아키텍처 최적화 대시보드는 계정 및 지역 전반에 걸쳐 스토리지 시스템과 구성을 한눈에 볼 수 있도록 지원합니다. 이 대시보드는 운영 효율성을 극대화하는 데 도움이 되는 인사이트와 권장 사항을 제공합니다. 구성의 아키텍처 최적화 상태, 사용 중인 스토리지 유형에 대한 아키텍처 최적화 프레임워크의 핵심 요소별로 정리된 구성 문제, 그리고 구성 문제 및 권장 사항 목록을 확인할 수 있습니다.

link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["잘 설계된 대시보드"]에 대해 자세히 알아보십시오.

Console의 잘 설계된 대시보드는 다음 스토리지 시스템에서 사용할 수 있습니다.

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Amazon FSx for NetApp ONTAP"]
* link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Microsoft Azure의 Cloud Volumes ONTAP"]




[[build-your-own-custom-rules]]
=== 사용자 지정 규칙 만들기

조직 표준 및 NetApp 모범 사례를 준수하도록 사용자 지정 규칙을 이해하기 쉬운 언어로 작성하세요. 모의 실행을 통해 규칙을 테스트한 다음, 모든 환경에서 실행되도록 예약할 수 있습니다.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["사용자 지정 규칙에 대해 자세히 알아보기"]
